# Generated by Django 3.1.4 on 2021-01-08 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20210108_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='Freelance',
            field=models.CharField(default='Available', max_length=30),
        ),
        migrations.AlterField(
            model_name='resume',
            name='Phone',
            field=models.CharField(max_length=12),
        ),
    ]
