# Generated by Django 3.1.4 on 2021-01-08 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20210108_2317'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resume',
            old_name='Address',
            new_name='City',
        ),
        migrations.AlterField(
            model_name='resume',
            name='Phone',
            field=models.CharField(max_length=13),
        ),
    ]
