# Generated by Django 3.1.4 on 2021-01-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0005_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('your_name', models.CharField(max_length=20)),
                ('your_email', models.CharField(max_length=20)),
                ('your_subject', models.CharField(max_length=20)),
                ('your_message', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Form',
        ),
    ]
